version: 2.1

references:
  workspace_root: &workspace_root
    ~/repo
  defaults: &defaults
    working_directory: *workspace_root

orbs:
  npm: sugarshin/npm@0.1.5

executors:
  node8:
    <<: *defaults
    docker:
      - image: circleci/node:8
  node10:
    <<: *defaults
    docker:
      - image: circleci/node:10
  node12:
    <<: *defaults
    docker:
      - image: circleci/node:12

jobs:
  test:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    steps:
      - checkout
      - npm/install:
          yarn: true
          cache-key: 'cache-{{ checksum "yarn.lock" }}'
      - run:
          name: Testing
          command: yarn test

workflows:
  tests:
    jobs:
      - test:
          name: test_node8
          e: node8
      - test:
          name: test_node10
          e: node10
      - test:
          name: test_node12
          e: node12
