version: 2.1

references:
  workspace_root: &workspace_root
    ~/repo
  defaults: &defaults
    working_directory: *workspace_root

orbs:
  npm: sugarshin/npm@0.1.5

executors:
  node8:
    <<: *defaults
    docker:
      - image: circleci/node:8
  node10:
    <<: *defaults
    docker:
      - image: circleci/node:10
  node12:
    <<: *defaults
    docker:
      - image: circleci/node:12

jobs:
  test:
    parameters:
      e:
        type: executor
      n:
        type: string
    executor: << parameters.e >>
    steps:
      - checkout
      - run:
          name: System information
          command: |
            node -v
            npm -v
      - npm/install:
          cache-key: cache-<< parameters.n >>-{{ checksum "package-lock.json" }}
      - run:
          name: Testing
          command: npm test

workflows:
  tests:
    jobs:
      - test:
          name: test_node8
          e: node8
          n: node8
      - test:
          name: test_node10
          e: node10
          n: node10
      - test:
          name: test_node12
          e: node12
          n: node12
      - npm/release:
          executor: node12
          tagging: true
          ssh-fingerprints: 80:38:86:c3:ea:ae:4c:f3:d7:25:55:b9:ab:83:1a:2a
          requires:
            - test_node8
            - test_node10
            - test_node12
          filters:
            branches:
              only: master
